apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy}}
        ports:
        - containerPort: {{ .Values.service.targetPort}}
          name: http
        - containerPort: {{ .Values.service.adminPort }}
          name: web
        livenessProbe:
          httpGet:
            path: "/actuator/info"
            port: {{ .Values.service.adminPort }}
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: {{ .Values.service.adminPort }}
            initialDelaySeconds: 90
            periodSeconds: 15
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
