apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    dev.okteto.com/generate-host: "true"
    app: {{ .Values.name }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  rules:
    - host: {{ .Values.service.hostname | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.port }}
    {{ if .Values.service.publicHostname}}
    - host: {{ .Values.service.publicHostname | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.port }}
    {{ end }}
